# Use the newer Travis-CI build templates based on the
# Debian Linux distribution "Xenial" release.
os: linux
dist: focal
language: minimal
env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
addons:
  sonarcloud:
    organization: fred78290-github
    token:
      secure: EkVnBHiVTlaKFX97f3k5pX5WByO17gNjJPM75/VlGsZ8mwr6qtSeNV+LH+MQW4QMD1JsIkOaGMwnDxHkepxojZ77QhmJgzPYY9KZnjwu7niDVY2V3xpEDDVijM/MYhvL15OIsxn94eIxqqVGKcWpRDC0pFoPhGX8z/7LuZaWYav+LBqVWCnmqqvnDChXAPVbDRJUKXtAZE0gIOJ7MdTpB8atTSfVbe++f9eXSmuAQjy9vyC6ZFmvl9Irap54XGd5/55URO+dzhW5BRDpXyTw6P51HQtNoYdlXjBnlv9W8fNQ9B+p97WKQgdPJblFrQa0PfDe/oM8CMAt0KkHIjx+djX2IJ7XDa/aivhHeESkc2/iTCr3K93QIBDjCHLGP5ExLyTl35eG+jX2MFSNU24aaoL2k5Ez5z4o8WIoNGxXUWvOI0aVFmhO/A9/DxY2tUwfDrteD3JYJi+Xi54vNI9Ajb0mQonGiY0X+qP/XsCqufCU33wQzeRn3z/2p4E56tOCkk6sBPh63ltasFSTlyc1B5zdmDPTGiqUuFS7blkTrZ1iPqPYBD+OE9VpWcrTBeF/Hmn/WX9v0eNQih/5FQxBHkhuQZ2g9GE/TBazAY7CvaDGhlAknXQjOVEOmZacGl7T/MgUT0uiBiVKjLCfstb0/JmUTrPPd+DMKjqZX7TZI9A=
cache:
  directories:
    - $HOME/.sonar/cache
    - vendor
jobs:
  include:
    - stage: build
      if: NOT(tag IS present OR commit_message =~ /\/ci-deploy/)
      install: true
      script:
        - make -e REGISTRY=fred78290 -e TAG=$TRAVIS_TAG container
        - sonar-scanner
    - stage: test
      if: NOT(tag IS present OR commit_message =~ /\/ci-deploy/)
      install: true
      script: make test-unit
    - stage: deploy
      if: tag IS present OR commit_message =~ /\/ci-deploy/
      services:
        - docker
      before_install:
        - mkdir -vp ~/.docker/cli-plugins/
        - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
        - chmod a+x ~/.docker/cli-plugins/docker-buildx
      install: true
      script:
        - docker buildx version
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker buildx create --use
        - make -e REGISTRY=fred78290 -e TAG=$TRAVIS_TAG container-push-manifest
        - cp out/linux/amd64/aws-autoscaler aws-autoscaler-amd64
        - cp out/linux/arm64/aws-autoscaler aws-autoscaler-arm64
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
          repo: Fred78290/kubernetes-aws-autoscaler
        file:
          - aws-autoscaler-amd64
          - aws-autoscaler-arm64
